Repository googleapis/java-dataproc-metastore, pull requests merged in 2021-03, with the labels that each got.

#2 chore: add proto-google-common-protos dependency
  grpc-google-cloud-dataproc-metastore-v1beta/pom.xml
Labels: automerge, cla: yes

#6 chore: migrate metastore to the PHP microgenerator
  .kokoro/build.sh
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/CreateBackupRequest.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/CreateBackupRequestOrBuilder.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/CreateMetadataImportRequest.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/CreateMetadataImportRequestOrBuilder.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/CreateServiceRequest.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/CreateServiceRequestOrBuilder.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/DeleteBackupRequest.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/DeleteBackupRequestOrBuilder.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/DeleteServiceRequest.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/DeleteServiceRequestOrBuilder.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/ExportMetadataRequest.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/ExportMetadataRequestOrBuilder.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/GetBackupRequest.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/GetMetadataImportRequest.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/GetMetadataImportRequestOrBuilder.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/GetServiceRequest.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/GetServiceRequestOrBuilder.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/ListBackupsRequest.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/ListBackupsRequestOrBuilder.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/ListBackupsResponse.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/ListMetadataImportsRequest.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/ListMetadataImportsRequestOrBuilder.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/ListMetadataImportsResponse.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/ListServicesRequest.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/ListServicesRequestOrBuilder.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/ListServicesResponse.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/MetadataExport.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/MetadataExportOrBuilder.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/MetadataImport.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/MetastoreProto.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/OperationMetadata.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/OperationMetadataOrBuilder.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/Restore.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/RestoreOrBuilder.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/RestoreServiceRequest.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/RestoreServiceRequestOrBuilder.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/Service.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/ServiceOrBuilder.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/UpdateMetadataImportRequest.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/UpdateMetadataImportRequestOrBuilder.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/UpdateServiceRequest.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/java/com/google/cloud/metastore/v1beta/UpdateServiceRequestOrBuilder.java
  proto-google-cloud-dataproc-metastore-v1beta/src/main/proto/google/cloud/metastore/v1beta/metastore.proto
  synth.metadata
Labels: api: metastore, automerge, cla: yes, context: partial

#8 chore: remove staging bucket v2
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: metastore, automerge, cla: yes, context: full
